// const defensores = [
// 	{ Gus: 6 },
// 	{ Pablo: 9 },
// 	{ Dani: 7 },
// 	{ Ernesto: 5 },
// 	{ Negro: 7 },
// 	{ Nico: 7 },
// ];
// const atacantes = [
// 	{ Fer: 9 },
// 	{ Rubio: 9 },
// 	{ Julián: 9 },
// 	{ Tomi: 7 },
// 	{ Rodri: 10 },
// 	{ Guido: 7 },
// 	{ 'Gus Primo': 7 },
// ];

// const variables = [{ 'Dani Romano': 7 }, { Tincho: 8 }, { 'Amigo de Dani': 7 }];

// const amarillo = [
// 	'Gus',
// 	'Dani',
// 	'Nico',
// 	'Rubio',
// 	'Fer',
// 	'Tincho',
// 	'Tomi',
// 	'Guido',
// ];
// const tricolor = [
// 	'Ernesto',
// 	'Pablo',
// 	'Negro',
// 	'Dani Romano',
// 	'Rodri',
// 	'Julian',
// 	'Gus Primo',
// 	'Amigo de Dani',
// ];

// const overall = Number(((defense + attack) / 2).toFixed(2));

// const players = [
// 	{
// 		playerName: 'Gus',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 6,
// 		attack: 4,
// 		overall: 5,
// 	},
// 	{
// 		playerName: 'Dani Romano',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 6,
// 		attack: 8,
// 		overall: 7,
// 	},
// 	{
// 		playerName: 'Pablo',
// 		isGoalKeeper: true,
// 		isPasser: true,
// 		defense: 9,
// 		attack: 7,
// 		overall: 8,
// 	},
// 	{
// 		playerName: 'Dani',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 7,
// 		attack: 6,
// 		overall: 6.5,
// 	},
// 	{
// 		playerName: 'Tincho',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 7,
// 		attack: 8,
// 		overall: 7.5,
// 	},
// 	{
// 		playerName: 'Nico L.',
// 		isGoalKeeper: true,
// 		isPasser: true,
// 		defense: 7,
// 		attack: 5,
// 		overall: 6,
// 	},
// 	{
// 		playerName: 'Rubio',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 6,
// 		attack: 9,
// 		overall: 7.5,
// 	},
// 	{
// 		playerName: 'Guido',
// 		isGoalKeeper: false,
// 		isPasser: false,
// 		defense: 7,
// 		attack: 7,
// 		overall: 6,
// 	},
// 	{
// 		playerName: 'Fer',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 3,
// 		attack: 9,
// 		overall: 7,
// 	},
// 	{
// 		playerName: 'Negro',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 7,
// 		attack: 5,
// 		overall: 6,
// 	},
// 	{
// 		playerName: 'Rodri',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 6,
// 		attack: 10,
// 		overall: 8,
// 	},
// 	{
// 		playerName: 'Gus Primo',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 8,
// 		attack: 7,
// 		overall: 7.5,
// 	},
// 	{
// 		playerName: 'Ernesto',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 5,
// 		attack: 5,
// 		overall: 5,
// 	},
// 	{
// 		playerName: 'Julián',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 3,
// 		attack: 9,
// 		overall: 7,
// 	},
// 	{
// 		playerName: 'Amigo de Dani',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 7,
// 		attack: 7,
// 		overall: 7,
// 	},
// 	{
// 		playerName: 'Tomi',
// 		isGoalKeeper: false,
// 		isPasser: true,
// 		defense: 6,
// 		attack: 7,
// 		overall: 6.5,
// 	},
// ];
