export const TYPES = {
    ADD_PLAYER: 'ADD_PLAYER',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    EDIT_PLAYER_STATS: 'EDIT_PLAYER_STATS',
    REMOVE_ALL_PLAYERS: 'REMOVE_ALL_PLAYERS',
    ASSIGN_TEAM1_PLAYER: 'ASSIGN_TEAM1_PLAYER',
    ASSIGN_TEAM2_PLAYER: 'ASSIGN_TEAM2_PLAYER',
    RESET_TEAMS: 'RESET_TEAMS'
}